version: "3.8"
   
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    env_file: .env.dev
  webapp:
    build: alpine_python_psycopg2
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./webapp:/code
    env_file: .env.dev
    entrypoint: /bin/sh ./docker-entrypoint.sh
  arduino_comm:
    build: alpine_python_psycopg2
    depends_on:
      - db
    volumes:
      - ./arduino_comm:/code
    env_file: .env.dev
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python run_arduino_comm.py
  webapp_tests:
    build: alpine_python_psycopg2
    depends_on:
      - db
    volumes:
      - ./webapp:/code
    env_file: .env.dev
    entrypoint: pytest
  arduino_comm_tests:
    build: alpine_python_psycopg2
    depends_on:
      - db
    volumes:
      - ./arduino_comm:/code
    env_file: .env.dev
    entrypoint: pytest
  pgadmin:
    image: truecharts/pgadmin4:6.16.0
    ports:
      - 15432:80
    depends_on:
      - db
    env_file: .env.dev
    volumes:
      - ./pgadmin:/var/lib/pgadmin
