version: "3.8"
   
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    env_file: .env.prod
  webapp:
    build: webapp
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./webapp:/code
    env_file: .env.prod
  arduino_comm:
    build: arduino_comm
    depends_on:
      - db
    volumes:
      - ./arduino_comm:/code
    env_file: .env.prod
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15432:80
    depends_on:
      - db
    env_file: .env.prod
    volumes:
      - ./pgadmin:/var/lib/pgadmin
