name: arduino_comm_dev
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - psycopg2
  - watchdog
  - serial
  - pip
  - pip:
    - pytest
    - pytest-cov
    - 'python-language-server[pycodestyle,pydocstyle]'
    - black
    - black-macchiato
