name: riwa_dev
channels:
  - defaults
dependencies:
  - python=3.8.5
  - numpy
  - psycopg2
  - pip
  - pip:
    - django
    - watchdog
    - pytest
    - pytest-cov
    - pytest-django
    - 'python-language-server[pycodestyle,pydocstyle]'
    - black
    - black-macchiato
